---

- include: packages_redhat.yml
  when: ansible_os_family == 'RedHat'

- include: packages_debian.yml
  when: ansible_os_family == 'Debian'

- name: Enable and start RabbitMQ server
  service:
    enabled: True
    name: 'rabbitmq-server'
    state: started
