---

- include: packages_redhat.yml
  when: ansible_os_family == 'RedHat'

- include: packages_debian.yml
  when: ansible_os_family == 'Debian'

- include: configuration.yml

- include: services.yml

- meta: flush_handlers

- include: plugins.yml
- include: vhost.yml
- include: user.yml
- include: policy.yml

- include: sanitycheck.yml
